environment:
  DISCORD_PUB_KEY: ${DISCORD_PUB_KEY}
  CLIENT_ID: ${CLIENT_ID}
  CLIENT_SECRET: ${CLIENT_SECRET}
packages:
  - name: pixeldailies
    actions:
      - name: count
        runtime: 'python:default'
        web: raw
